const image = (fileName: string) => `/assets/${fileName}`;

export const resortSeedData = [
  {
    sourceId: "lakeridge-ski-resort",
    name: "Lakeridge Ski Resort",
    address: "790 Chalk Lake Rd, Uxbridge, ON L9P 1R4",
    continent: "North America",
    country: "Canada",
    region: "Ontario",
    coordinates: { lat: 44.04597402067868, lng: -79.06573258279116 },
    rate: 67.47,
    contact: "(905) 649-2058",
    email: "admin@lakeridgeresort.ca",
    phone: "(905) 649-2058",
    tollFree: "1-877-350-3640",
    googleMapsUrl: "https://maps.app.goo.gl/3J7NiWbwWLPE2xJp9",
    website: "http://www.ski-lakeridge.com/",
    image: image("lakeridge-ski-resort.webp"),
    trailMap: image("lakeridge-ski-resort-trail-map.jpg"),
    dayTicketPrice: 67.47,
    lessonsPrice: 123.12,
    skiRentalPrice: 55,
    snowBoardRentalPrice: 66,
    tubbingPrice: 30,
    rating: 4.3,
    hasAccommodations: false,
    hasCrossCountry: false,
    hasLessons: true,
    hasSnowshoeing: false,
    hasSpa: false,
    hasTubing: true,
    hoursOfOperation: {
      sunday: "9:00am - 9:30pm",
      monday: "9:00am - 9:30pm",
      tuesday: "9:00am - 9:30pm",
      wednesday: "9:00am - 9:30pm",
      thursday: "9:00am - 9:30pm",
      friday: "9:00am - 9:30pm",
      saturday: "9:00am - 9:30pm",
    },
    runs: { black: 5, blue: 3, doubleBlack: 2, freeStyle: 19, green: 6 },
  },
  {
    sourceId: "dagmar-ski-resort",
    name: "Dagmar Ski Resort",
    address: "1220 Lake Ridge Rd, Uxbridge, ON L9L 1V7",
    continent: "North America",
    country: "Canada",
    region: "Ontario",
    coordinates: { lat: 44.02314189216543, lng: -79.04741821453386 },
    rate: 66.37,
    dayTicketPrice: 66.37,
    contact: "(905) 649-2002",
    email: "info@skidagmar.com",
    phone: "(905) 649-2002",
    googleMapsUrl: "https://maps.app.goo.gl/m7aFQ1mktoy449cC6",
    website: "http://www.skidagmar.com/",
    image: image("dagmar-ski-resort.jpg"),
    trailMap: image("lakeridge-ski-resort-trail-map.jpg"),
    lessonsPrice: 116.81,
    skiRentalPrice: 48.67,
    snowBoardRentalPrice: 60.18,
    tubbingPrice: 0,
    rating: 4.2,
    hasAccommodations: false,
    hasCrossCountry: false,
    hasLessons: true,
    hasSnowshoeing: false,
    hasSpa: false,
    hasTubing: false,
    hoursOfOperation: {
      sunday: "9:00am - 9:30pm",
      monday: "9:00am - 9:30pm",
      tuesday: "CLOSED",
      wednesday: "10:00am - 9:30pm",
      thursday: "10:00am - 9:30pm",
      friday: "10:00am - 9:30pm",
      saturday: "9:00am - 9:30pm",
    },
    runs: { black: 1, blue: 5, doubleBlack: 2, freeStyle: 14, green: 6 },
  },
  {
    sourceId: "brimacombe",
    name: "Brimacombe",
    address: "4098 Regional Road 9, Orono, ON L0B 1M0",
    continent: "North America",
    country: "Canada",
    region: "Ontario",
    coordinates: { lat: 44.06901178082853, lng: -78.5731371079196 },
    rate: 65,
    dayTicketPrice: 65,
    contact: "(905) 983-5983",
    email: "info@brimacombe.ca",
    phone: "(905) 983-5983",
    tollFree: "1.877.672.2582",
    googleMapsUrl: "https://maps.app.goo.gl/y2c4XGM9iTEwzmh76",
    website: "http://brimacombe.ca/",
    image: image("brimacombe.jpg"),
    trailMap: image("brimacombe-trail-map.jpg"),
    lessonsPrice: 120,
    skiRentalPrice: 77,
    snowBoardRentalPrice: 77,
    tubbingPrice: 0,
    rating: 4.2,
    hasAccommodations: true,
    hasCrossCountry: false,
    hasLessons: true,
    hasSnowshoeing: false,
    hasSpa: false,
    hasTubing: false,
    hoursOfOperation: {
      sunday: "9:00am - 4:30pm",
      monday: "9:00am - 9:30pm",
      tuesday: "CLOSED",
      wednesday: "9:00am - 9:30pm",
      thursday: "9:00am - 9:30pm",
      friday: "9:00am - 9:30pm",
      saturday: "9:00am - 9:30pm",
    },
    runs: { black: 8, blue: 6, doubleBlack: 0, freeStyle: 0, green: 8 },
  },
  {
    sourceId: "snow-valley-ski-resort",
    name: "Ski Snow Valley",
    address: "2632 Vespra Valley Rd, Minesing ON L9X 0G8",
    continent: "North America",
    country: "Canada",
    region: "Ontario",
    coordinates: { lat: 44.46119110037171, lng: -79.7835534199466 },
    rate: 65,
    dayTicketPrice: 65,
    contact: "(705) 721-7669",
    email: "info@skisnowvalley.com",
    phone: "(705) 721-7669",
    tollFree: "1-877-404-4744",
    googleMapsUrl: "https://maps.app.goo.gl/HsGTUq8paByDS8z4A",
    website: "http://www.skisnowvalley.com/",
    image: image("lakeridge-ski-resort.webp"),
    trailMap: image("lakeridge-ski-resort-trail-map.jpg"),
    lessonsPrice: 139,
    skiRentalPrice: 70,
    snowBoardRentalPrice: 70,
    tubbingPrice: 27,
    rating: 4.3,
    hasAccommodations: false,
    hasCrossCountry: false,
    hasLessons: true,
    hasSnowshoeing: true,
    hasSpa: false,
    hasTubing: true,
    hasZipline: true,
    hoursOfOperation: {
      sunday: "9:00am - 9:00pm",
      monday: "9:00am - 4:00pm",
      tuesday: "9:00am - 9:00pm",
      wednesday: "19:00am - 9:00pm",
      thursday: "19:00am - 9:00pm",
      friday: "19:00am - 9:00pm",
      saturday: "9:00am - 9:00pm",
    },
    runs: { black: 5, blue: 4, doubleBlack: 1, freeStyle: 0, green: 6 },
  },
  {
    sourceId: "horseshoe-valley-resort",
    name: "Horseshoe Valley Resort",
    address: "1101 Horseshoe Valley Rd W, Barrie, ON L4M 4Y8",
    continent: "North America",
    country: "Canada",
    region: "Ontario",
    coordinates: { lat: 44.59429988048484, lng: -79.68125046375664 },
    rate: 99,
    dayTicketPrice: 99,
    contact: "(705) 835-2790",
    email: "info@horseshoeresort.com",
    phone: "(705) 835-2790",
    googleMapsUrl: "https://maps.app.goo.gl/bzCpVSuKs9mPU3BNA",
    website: "http://horseshoeresort.com/",
    image: image("horseshoe-valley-resort.webp"),
    trailMap: image("lakeridge-ski-resort-trail-map.jpg"),
    lessonsPrice: 159,
    skiRentalPrice: 79,
    snowBoardRentalPrice: 79,
    tubbingPrice: 39,
    rating: 4.1,
    hasAccommodations: true,
    hasCrossCountry: true,
    hasLessons: true,
    hasSnowshoeing: true,
    hasSpa: true,
    hasTubing: true,
    hoursOfOperation: {
      monday: "9:00am - 9:00pm",
      tuesday: "9:00am - 9:00pm",
      wednesday: "9:00am - 9:00pm",
      thursday: "9:00am - 9:00pm",
      friday: "9:00am - 9:00pm",
      saturday: "9:00am - 9:00pm",
      sunday: "9:00am - 9:00pm",
    },
    runs: { black: 2, blue: 15, doubleBlack: 0, freeStyle: 27, green: 8 },
  },
  {
    sourceId: "blue-mountain",
    name: "Blue Mountain",
    address: "190 Gord Canning Drive Blue Mountains, Ontario, Canada L9Y 1C2",
    continent: "North America",
    country: "Canada",
    region: "Ontario",
    coordinates: { lat: 44.55091707586931, lng: -80.31056434810445 },
    rate: 100,
    dayTicketPrice: 100,
    contact: "1-833-583-2583",
    email: "mail@bluemountain.ca",
    phone: "1-833-583-2583",
    tollFree: "1-833-583-2583",
    googleMapsUrl: "https://maps.app.goo.gl/mX4YUs7faBFud9sX8",
    website: "https://www.bluemountain.ca/",
    image: image("blue-mountain.jpg"),
    trailMap: image("blue-mountain-trail-map.jpg"),
    lessonsPrice: 279,
    skiRentalPrice: 109,
    snowBoardRentalPrice: 109,
    tubbingPrice: 84.84,
    rating: 4.4,
    hasAccommodations: true,
    hasCrossCountry: false,
    hasLessons: true,
    hasSnowshoeing: true,
    hasSpa: true,
    hasTubing: true,
    hoursOfOperation: {
      monday: "9:00am - 9:00pm",
      tuesday: "9:00am - 9:00pm",
      wednesday: "9:00am - 9:00pm",
      thursday: "9:00am - 9:00pm",
      friday: "9:00am - 9:00pm",
      saturday: "9:00am - 9:00pm",
      sunday: "9:00am - 9:00pm",
    },
    runs: { black: 9, blue: 19, doubleBlack: 16, freeStyle: 60, green: 12 },
  },
  {
    sourceId: "glen-eden",
    name: "Glen Eden",
    address: "5234 Kelso Rd, Milton, ON L9T 2X7",
    continent: "North America",
    country: "Canada",
    region: "Ontario",
    coordinates: { lat: 43.55418055900003, lng: -79.93414693948958 },
    rate: 65,
    dayTicketPrice: 65,
    contact: "(905) 878-5011",
    email: "gleneden@hrca.on.ca",
    phone: "(905) 878-5011",
    googleMapsUrl: "https://maps.app.goo.gl/B1FXSZ1VtYbVTsaXA",
    website: "https://gleneden.on.ca/",
    image: image("glen-eden.webp"),
    trailMap: image("glen-eden-trail-map.webp"),
    lessonsPrice: 125,
    skiRentalPrice: 52,
    snowBoardRentalPrice: 52,
    tubbingPrice: 0,
    rating: 4.2,
    hasAccommodations: false,
    hasCrossCountry: false,
    hasLessons: true,
    hasSnowshoeing: false,
    hasSpa: false,
    hasTubing: false,
    hoursOfOperation: {
      monday: "8:30am - 9:30pm",
      tuesday: "8:30am - 9:30pm",
      wednesday: "8:30am - 9:30pm",
      thursday: "8:30am - 9:30pm",
      friday: "8:30am - 9:30pm",
      saturday: "8:30am - 9:30pm",
      sunday: "8:30am - 9:30pm",
    },
    runs: { black: 2, blue: 4, doubleBlack: 0, freeStyle: 17, green: 7 },
  },
  {
    sourceId: "chicopee",
    name: "Chicopee",
    address: "396 Morrison Road, Kitchener, ON N2A 2Z6",
    continent: "North America",
    country: "Canada",
    region: "Ontario",
    coordinates: { lat: 43.50150295771778, lng: -80.42101373098909 },
    rate: 65,
    dayTicketPrice: 65,
    contact: "(519) 894-5610",
    email: "guestservices@chicopee.ca",
    phone: "(519) 894-5610",
    googleMapsUrl: "https://maps.app.goo.gl/GSNWkGQzo5aHdWmf9",
    website: "http://www.discoverchicopee.com/",
    image: image("chicopee.jpg"),
    trailMap: image("chicopee-trail-map.jpg"),
    lessonsPrice: 350,
    skiRentalPrice: 53,
    snowBoardRentalPrice: 53,
    tubbingPrice: 0,
    rating: 4.2,
    hasAccommodations: false,
    hasCrossCountry: false,
    hasLessons: true,
    hasSnowshoeing: false,
    hasSpa: false,
    hasTubing: false,
    hoursOfOperation: {
      monday: "9:00am - 9:00pm",
      tuesday: "9:00am - 9:00pm",
      wednesday: "9:00am - 9:00pm",
      thursday: "9:00am - 9:00pm",
      friday: "9:00am - 9:00pm",
      saturday: "9:00am - 9:00pm",
      sunday: "9:00am - 9:00pm",
    },
    runs: { black: 5, blue: 5, doubleBlack: 0, freeStyle: 13, green: 3 },
  },
  {
    sourceId: "caledon-ski-club",
    name: "Caledon Ski Club",
    address: "17431 Mississauga Road, Caledon, Ontario L7K 0E9",
    continent: "North America",
    country: "Canada",
    region: "Ontario",
    coordinates: { lat: 43.856306447577786, lng: -80.00755054550318 },
    rate: 85,
    dayTicketPrice: 85,
    contact: "1-800-363-7669",
    email: "admin@caledonskiclub.on.ca",
    phone: "1-800-363-7669",
    googleMapsUrl: "https://maps.app.goo.gl/UqTeQ1vjSiSMV1CK7",
    website: "http://caledonskiclub.com/",
    image: image("calendon.jpg"),
    trailMap: image("caledon-trail-map.jpg"),
    lessonsPrice: 0,
    skiRentalPrice: 74.99,
    snowBoardRentalPrice: 74.99,
    tubbingPrice: 0,
    rating: 4.6,
    hasAccommodations: false,
    hasCrossCountry: false,
    hasLessons: true,
    hasSnowshoeing: false,
    hasSpa: false,
    hasTubing: false,
    hoursOfOperation: {
      sunday: "8:30am - 4:00pm",
      monday: "8:30am - 4:00pm",
      tuesday: "8:30am - 4:00pm",
      wednesday: "8:30am - 4:00pm",
      thursday: "8:30am - 4:00pm",
      friday: "8:30am - 4:00pm",
      saturday: "8:30am - 4:00pm",
    },
    runs: { black: 0, blue: 0, doubleBlack: 0, freeStyle: 27, green: 27 },
  },
] as const;

type TrackCondition = {
  name: string;
  condition: string;
  difficulty: string;
};

const tracks = (entries: Array<[string, string]>, condition = "open") =>
  entries.map(([name, difficulty]) => ({ name, condition, difficulty }));

export const trackConditionsSeed: Record<string, TrackCondition[]> = {
  "lakeridge-ski-resort": tracks([
    ["Sunnyside", "black"], ["Mogul Alley", "double-black"], ["Banked Slalom Run", "free-style"],
    ["Short Cut", "green"], ["Collectors", "green"], ["One Way", "green"], ["Beginners Area", "green"],
    ["Little Razors", "free-style"], ["Highway", "green"], ["Razors Edge Terrain Park", "free-style"],
    ["Bail Out", "black"], ["Rieky's Run", "double-black"], ["Upper Chute", "black"], ["Lower Chute", "black"],
    ["Valley Road", "blue"], ["Freeway", "black"], ["East Avenue", "blue"], ["Bridge-Trail", "blue"], ["Little Rogers", "green"],
  ]),
  "dagmar-ski-resort": tracks([
    ["Park View", "green"], ["The Chute", "blue"], ["Little Momma", "green"], ["Pony", "green"],
    ["Rendez Vous", "blue"], ["Bomber", "black"], ["Upper Lovers Lane", "green"], ["Lower Lovers Lane", "green"],
    ["Club House", "blue"], ["Favourite", "green"], ["Alleyway", "blue"], ["Elbow", "blue"], ["The Dagger", "double-black"], ["The Glades", "double-black"],
  ]),
  brimacombe: tracks([
    ["Park Avenue", "green"], ["Pete’s Elbow", "green"], ["Snow Bowl", "green"], ["Standard", "blue"], ["Bambi", "green"],
    ["Ladies Downhill", "blue"], ["Ben’s Bump", "black"], ["Bowl", "black"], ["Tower Run", "black"], ["Timberline", "black"],
    ["Flyer", "blue"], ["Cowpath", "green"], ["Kid’s Stuff", "green"], ["Club House Run", "blue"], ["West Ridge", "black"],
    ["Rutherford’s Cut", "black"], ["Richards’ Landing", "black"], ["Challenger", "black"], ["Whistler", "blue"], ["Sunny Side", "blue"],
    ["Nice and Easy", "green"], ["Farmer’s Field", "green"],
  ]),
  "snow-valley-ski-resort": tracks([
    ["Garfield", "green"], ["Snoopy", "green"], ["Trudys Way", "blue"], ["Pennys", "black"], ["Schuss", "black"],
    ["Highland Trail", "green"], ["Family", "green"], ["Racer", "black"], ["Hard Knox", "black"], ["Front", "blue"],
    ["Whistler", "blue"], ["Recken Run", "green"], ["Vertigo", "double-black"], ["Huxtable", "blue"], ["Oh Chute", "black"], ["Kidz Village", "green"],
  ]),
  "horseshoe-valley-resort": tracks([
    ["Ponyback", "green"], ["Pinto", "green"], ["Hungry Hollow", "green"], ["Roundup", "green"], ["Donkey Serenade", "green"],
    ["Pony Express", "green"], ["Canter", "green"], ["Mule Train", "green"], ["Steeplechase", "blue"], ["Flying Mare", "blue"],
    ["Pony Tail", "blue"], ["Ramey's Return", "blue"], ["Saddleback", "blue"], ["Stallion Slide", "blue"], ["Duster", "blue"],
    ["Nightmare Ride", "blue"], ["Stampede", "blue"], ["The Wave", "blue"], ["Shaggy Mane", "blue"], ["The Zipper", "blue"],
    ["Bushwacker", "blue"], ["Bronco", "blue"], ["Rodeo", "blue"], ["Race Hill", "black"], ["Horsefeathers", "black"],
    ["Horsefly Hop", "free-style"], ["Bullpen", "free-style"],
  ]),
  "glen-eden": tracks([
    ["Escarpment Run", "green"], ["Night Hawk", "green"], ["Butternut", "blue"], ["Falcon", "blue"], ["Sidewinder", "blue"],
    ["Twister", "blue"], ["Boomerang", "black"], ["Challenger", "black"], ["Quarry Run", "free-style"], ["Scimitar", "free-style"],
    ["Comet", "green"], ["Milky Way", "green"], ["Little Dipper", "free-style"], ["Shooting Star", "free-style"], ["Bumble Bee", "green"],
    ["Grasshopper", "green"], ["Monarch", "green"],
  ]),
  "chicopee": tracks([
    ["Discover", "green"], ["Adventure", "green"], ["Bridge", "blue"], ["Freedom", "blue"], ["Mount St. Louis Moonstone Way", "green"],
    ["Wishbone", "blue"], ["Easy Rider", "black"], ["North", "blue"], ["Mic Mac", "black"], ["Chicane", "black"],
    ["Roughshod", "black"], ["Applebowl", "black"], ["Racer's Alley", "blue"],
  ]),
  "caledon-ski-club": tracks([
    ["Alley Way", "green"], ["Boughner's Boogie", "green"], ["Snow Park", "green"], ["Dodds' Dip", "green"], ["Eaton's Annex", "green"],
    ["Harold's Headstander", "green"], ["Holden's Hwy", "green"], ["Kendall's Kandihar", "green"], ["Kenne's Kicker", "green"], ["Kids' Buel", "green"],
    ["Knight Flight", "green"], ["Larry's Line", "green"], ["Lower Road", "green"], ["MacKenzie Trail", "green"], ["Moonbeam", "green"],
    ["O.K. Ross Run", "green"], ["Philpott's Folly", "green"], ["Porter's Pipeline", "green"], ["Quick Link", "green"], ["Roadrunner", "green"],
    ["Sidewinder", "green"], ["Snowy's Glade", "green"], ["Soules' Skyway", "green"], ["The Yeighway Highway", "green"], ["West Hill", "green"],
    ["Wortley's Wiggle", "green"], ["Zoe's Line", "green"],
  ]).map((track) => track.name === "Kids' Buel" ? { ...track, condition: "close" } : track),
};
