{
  [
    {
      address: "790 Chalk Lake Rd, Uxbridge, ON L9P 1R4",
      coordinates: { lat: 44.04597402067868, lng: -79.06573258279116 },
      dayTicketPrice: 67.47,
      email: "admin@lakeridgeresort.ca",
      googleMapsUrl: "https://maps.app.goo.gl/3J7NiWbwWLPE2xJp9",
      resortId: "lakeridge-ski-resort",
      image: lakeridgeSkiResortImg, // need to be update for something better
      hasAccommodations: false,
      hasCrossCountry: false,
      hasLessons: true,
      hasSnowshoeing: false,
      hasSpa: false,
      hasTubing: true,
      lessonsPrice: 123.12,
      name: "Lakeridge Ski Resort",
      phone: "(905) 649-2058",
      rating: 4.3,
      skiRentalPrice: 55,
      snowBoardRentalPrice: 66,
      runs: { black: 5, blue: 3, doubleBlack: 2, freeStyle: 19, green: 6 },
      ticketUrl:
        "https://ski-lakeridge.resortstore.net/en/catalogue/categories/",
      tollFree: "1-877-350-3640",
      trackConditions: [
        { name: "Sunnyside", condition: "open", difficulty: "black" },
        { name: "Mogul Alley", condition: "open", difficulty: "double-black" },
        {
          name: "Banked Slalom Run",
          condition: "open",
          difficulty: "free-style",
        },
        { name: "Short Cut", condition: "open", difficulty: "green" },
        { name: "Collectors", condition: "open", difficulty: "green" },
        { name: "One Way", condition: "open", difficulty: "green" },
        { name: "Beginners Area", condition: "open", difficulty: "green" },
        { name: "Little Razors", condition: "open", difficulty: "free-style" },
        { name: "Highway", condition: "open", difficulty: "green" },
        {
          name: "Razors Edge Terrain Park",
          condition: "open",
          difficulty: "free-style",
        },
        { name: "Bail Out", condition: "open", difficulty: "black" },
        { name: "Rieky's Run", condition: "open", difficulty: "double-black" },
        { name: "Upper Chute", condition: "open", difficulty: "black" },
        { name: "Lower Chute", condition: "open", difficulty: "black" },
        { name: "Valley Road", condition: "open", difficulty: "blue" },
        { name: "Freeway", condition: "open", difficulty: "black" },
        { name: "East Avenue", condition: "open", difficulty: "blue" },
        { name: "Bridge-Trail", condition: "open", difficulty: "blue" },
        { name: "Little Rogers", condition: "open", difficulty: "green" },
      ],
      trailMap: lakeridgeSkiResortTrailMap,
      tubbingPrice: 30,
      website: "http://www.ski-lakeridge.com/",
    },
    {
      address: "1220 Lake Ridge Rd, Uxbridge, ON L9L 1V7",
      coordinates: { lat: 44.02314189216543, lng: -79.04741821453386 },
      dayTicketPrice: 66.37,
      email: "info@skidagmar.com",
      googleMapsUrl: "https://maps.app.goo.gl/m7aFQ1mktoy449cC6",
      resortId: "dagmar-ski-resort",
      image: dagmarSkiResortImg,
      hasAccommodations: false,
      hasCrossCountry: false,
      hasLessons: true,
      hasSnowshoeing: false,
      hasSpa: false,
      hasTubing: false,
      lessonsPrice: 116.81,
      name: "Dagmar Ski Resort",
      phone: "(905) 649-2002",
      rating: 4.2,
      skiRentalPrice: 48.67,
      snowBoardRentalPrice: 60.18,
      runs: { black: 1, blue: 5, doubleBlack: 2, freeStyle: 14, green: 6 },
      trackConditions: [
        { name: "Park View", condition: "open", difficulty: "green" },
        { name: "The Chute", condition: "open", difficulty: "blue" },
        { name: "Little Momma", condition: "open", difficulty: "green" },
        { name: "Pony", condition: "open", difficulty: "green" },
        { name: "Rendez Vous", condition: "open", difficulty: "blue" },
        { name: "Bomber", condition: "open", difficulty: "black" },
        { name: "Upper Lovers Lane", condition: "open", difficulty: "green" },
        { name: "Lower Lovers Lane", condition: "open", difficulty: "green" },
        { name: "Club House", condition: "open", difficulty: "blue" },
        { name: "Favourite", condition: "open", difficulty: "green" },
        { name: "Alleyway", condition: "open", difficulty: "blue" },
        { name: "Elbow", condition: "open", difficulty: "blue" },
        { name: "The Dagger", condition: "open", difficulty: "double-black" },
        { name: "The Glades", condition: "open", difficulty: "double-black" },
      ],
      trailMap: dagmarSkiResortTrailMap,
      tubbingPrice: 0, // not update
      website: "http://www.skidagmar.com/",
    },
    {
      address: "4098 Regional Road 9, Orono, ON L0B 1M0",
      coordinates: { lat: 44.06901178082853, lng: -78.5731371079196 },
      dayTicketPrice: 65,
      email: "info@brimacombe.ca",
      googleMapsUrl: "https://maps.app.goo.gl/y2c4XGM9iTEwzmh76",
      resortId: "brimacombe",
      image: brimacombeImg,
      hasAccommodations: true,
      hasCrossCountry: false,
      hasLessons: true,
      hasSnowshoeing: false,
      hasSpa: false,
      hasTubing: false,
      lessonsPrice: 120,
      name: "Brimacombe",
      phone: "(905) 983-5983",
      rating: 4.2,
      runs: { black: 8, blue: 6, doubleBlack: 0, freeStyle: 0, green: 8 },
      skiRentalPrice: 77,
      snowBoardRentalPrice: 77,
      ticketUrl: "https://brimacombe.ca/shop-online/",
      tollFree: "1.877.672.2582",
      trackConditions: [
        { name: "Park Avenue", condition: "open", difficulty: "green" },
        { name: "Pete’s Elbow", condition: "open", difficulty: "green" },
        { name: "Snow Bowl", condition: "open", difficulty: "green" },
        { name: "Standard", condition: "open", difficulty: "blue" },
        { name: "Bambi", condition: "open", difficulty: "green" },
        { name: "Ladies Downhill", condition: "closed", difficulty: "blue" },
        { name: "Ben’s Bump", condition: "closed", difficulty: "black" },
        { name: "Bowl", condition: "closed", difficulty: "black" },
        { name: "Tower Run", condition: "closed", difficulty: "black" },
        { name: "Timberline", condition: "closed", difficulty: "black" },
        { name: "Flyer", condition: "closed", difficulty: "blue" },
        { name: "Cowpath", condition: "closed", difficulty: "green" },
        { name: "Kid’s Stuff", condition: "closed", difficulty: "green" },
        { name: "Club House Run", condition: "closed", difficulty: "blue" },
        { name: "West Ridge", condition: "closed", difficulty: "black" },
        { name: "Rutherford’s Cut", condition: "closed", difficulty: "black" },
        { name: "Richards’ Landing", condition: "closed", difficulty: "black" },
        { name: "Challenger", condition: "closed", difficulty: "black" },
        { name: "Whistler", condition: "closed", difficulty: "blue" },
        { name: "Sunny Side", condition: "closed", difficulty: "blue" },
        { name: "Nice and Easy", condition: "closed", difficulty: "green" },
        { name: "Farmer’s Field", condition: "closed", difficulty: "green" },
      ],
      trailMap: brimacombeTrailMap,
      tubbingPrice: 0,
      website: "http://brimacombe.ca/",
    },
    {
      address: "2632 Vespra Valley Rd, Minesing ON L9X 0G8",
      coordinates: { lat: 44.46119110037171, lng: -79.7835534199466 },
      dayTicketPrice: 65,
      email: "info@skisnowvalley.com",
      googleMapsUrl: "https://maps.app.goo.gl/HsGTUq8paByDS8z4A",
      resortId: "snow-valley-ski-resort",
      image: lakeridgeSkiResortImg,
      hasAccommodations: false,
      hasCrossCountry: false,
      hasLessons: true,
      hasSnowshoeing: true,
      hasSpa: false,
      hasTubing: true,
      hasZipline: true,
      lessonsPrice: 139,
      name: "Snow Valley Ski Resort",
      phone: "(705) 721-7669",
      rating: 4.3,
      runs: { black: 5, blue: 4, doubleBlack: 1, freeStyle: 0, green: 6 },
      skiRentalPrice: 70,
      snowBoardRentalPrice: 70,
      ticketUrl:
        "https://skisnowvalley.resortstore.net/en/catalogue/categories/",
      tollFree: "1-877-404-4744",
      trackConditions: [
        { name: "Garfield", condition: "open", difficulty: "green" },
        { name: "Snoopy", condition: "open", difficulty: "green" },
        { name: "Trudys Way", condition: "open", difficulty: "blue" },
        { name: "Pennys", condition: "open", difficulty: "black" },
        { name: "Schuss", condition: "open", difficulty: "black" },
        { name: "Highland Trail", condition: "open", difficulty: "green" },
        { name: "Family", condition: "open", difficulty: "green" },
        { name: "Racer", condition: "open", difficulty: "black" },
        { name: "Hard Knox", condition: "open", difficulty: "black" },
        { name: "Front", condition: "open", difficulty: "blue" },
        { name: "Whistler", condition: "open", difficulty: "blue" },
        { name: "Recken Run", condition: "open", difficulty: "green" },
        { name: "Vertigo", condition: "open", difficulty: "double-black" },
        { name: "Huxtable", condition: "open", difficulty: "blue" },
        { name: "Oh Chute", condition: "open", difficulty: "black" },
        { name: "Kidz Village", condition: "open", difficulty: "green" },
      ],
      trailMap: lakeridgeSkiResortTrailMap,
      tubbingPrice: 27,
      website: "http://www.skisnowvalley.com/",
    },
    {
      address: "1101 Horseshoe Valley Rd W, Barrie, ON L4M 4Y8",
      coordinates: { lat: 44.59429988048484, lng: -79.68125046375664 },
      dayTicketPrice: 99,
      email: "info@horseshoeresort.com",
      googleMapsUrl: "https://maps.app.goo.gl/bzCpVSuKs9mPU3BNA",
      resortId: "horseshoe-valley-resort",
      image: horseshoeValleyResortImg,
      hasAccommodations: true,
      hasCrossCountry: true,
      hasLessons: true,
      hasSnowshoeing: true,
      hasSpa: true,
      hasTubing: true,
      lessonsPrice: 159,
      name: "Horseshoe Valley Resort",
      phone: "(705) 835-2790",
      rating: 4.1,
      skiRentalPrice: 79,
      snowBoardRentalPrice: 79,
      runs: { black: 2, blue: 15, doubleBlack: 0, freeStyle: 27, green: 8 },
      ticketUrl: "https://shop.horseshoeresort.com/tickets",
      trackConditions: [
        { name: "Ponyback", condition: "open", difficulty: "green" },
        { name: "Pinto", condition: "open", difficulty: "green" },
        { name: "Hungry Hollow", condition: "open", difficulty: "green" },
        { name: "Roundup", condition: "open", difficulty: "green" },
        { name: "Donkey Serenade", condition: "open", difficulty: "green" },
        { name: "Pony Express", condition: "open", difficulty: "green" },
        { name: "Canter", condition: "open", difficulty: "green" },
        { name: "Mule Train", condition: "open", difficulty: "green" },
        { name: "Steeplechase", condition: "open", difficulty: "blue" },
        { name: "Flying Mare", condition: "open", difficulty: "blue" },
        { name: "Pony Tail", condition: "open", difficulty: "blue" },
        { name: "Ramey's Return", condition: "open", difficulty: "blue" },
        { name: "Saddleback", condition: "open", difficulty: "blue" },
        { name: "Stallion Slide", condition: "open", difficulty: "blue" },
        { name: "Duster", condition: "open", difficulty: "blue" },
        { name: "Nightmare Ride", condition: "open", difficulty: "blue" },
        { name: "Stampede", condition: "open", difficulty: "blue" },
        { name: "The Wave", condition: "open", difficulty: "blue" },
        { name: "Shaggy Mane", condition: "open", difficulty: "blue" },
        { name: "The Zipper", condition: "open", difficulty: "blue" },
        { name: "Bushwacker", condition: "open", difficulty: "blue" },
        { name: "Bronco", condition: "open", difficulty: "blue" },
        { name: "Rodeo", condition: "open", difficulty: "blue" },
        { name: "Race Hill", condition: "open", difficulty: "black" },
        { name: "Horsefeathers", condition: "open", difficulty: "black" },
        { name: "Horsefly Hop", condition: "open", difficulty: "free-style" },
        { name: "Bullpen", condition: "open", difficulty: "free-style" },
      ],
      trailMap: horseshoeValleyResortTrailMap,
      tubbingPrice: 39,
      website: "http://horseshoeresort.com/",
    },
    {
      address: "190 Gord Canning Drive Blue Mountains, Ontario, Canada L9Y 1C2",
      coordinates: { lat: 44.55091707586931, lng: -80.31056434810445 },
      dayTicketPrice: 100,
      email: "mail@bluemountain.ca",
      googleMapsUrl: "https://maps.app.goo.gl/mX4YUs7faBFud9sX8",
      resortId: "blue-mountain",
      image: blueMountainImg,
      hasAccommodations: true,
      hasCrossCountry: false,
      hasLessons: true,
      hasSnowshoeing: true,
      hasSpa: true,
      hasTubing: true,
      lessonsPrice: 279,
      name: "Blue Mountain",
      phone: "1-833-583-2583",
      rating: 4.4,
      skiRentalPrice: 109,
      snowBoardRentalPrice: 109,
      runs: { black: 9, blue: 19, doubleBlack: 16, freeStyle: 60, green: 12 },
      ticketUrl:
        "https://www.bluemountain.ca/plan-your-trip/day-tickets/winter-lift-tickets",
      trackConditions: [
        { name: "Finally", condition: "open", difficulty: "blue" },
        {
          name: "Grove Terrain Park",
          condition: "open",
          difficulty: "free-style",
        },
        { name: "Southern Cross", condition: "open", difficulty: "green" },
        {
          name: "Badlands Terrain Park",
          condition: "open",
          difficulty: "free-style",
        },
        { name: "Founders", condition: "open", difficulty: "blue" },
        { name: "Juicer", condition: "open", difficulty: "blue" },
        { name: "Butternut", condition: "open", difficulty: "blue" },
        { name: "Gord's Groove", condition: "open", difficulty: "green" },
        {
          name: "Lower Orchard Glades",
          condition: "open",
          difficulty: "double-black",
        },
        {
          name: "Upper Orchard Glades",
          condition: "open",
          difficulty: "double-black",
        },
        {
          name: "Bear Trail Glades",
          condition: "open",
          difficulty: "double-black",
        },
        { name: "Cruiser", condition: "open", difficulty: "blue" },
        { name: "Explorer", condition: "open", difficulty: "green" },
        {
          name: "Old South Glades",
          condition: "open",
          difficulty: "double-black",
        },
        { name: "Big Baby", condition: "open", difficulty: "green" },
        { name: "Dr. Doug", condition: "open", difficulty: "blue" },
        { name: "Little Ripper", condition: "open", difficulty: "green" },
        { name: "Sunrise", condition: "open", difficulty: "blue" },
        { name: "Crooked Oak", condition: "open", difficulty: "black" },
        { name: "Enchanted Forest", condition: "open", difficulty: "green" },
        { name: "Mary Jane's Lane", condition: "open", difficulty: "green" },
        { name: "Waterfall", condition: "open", difficulty: "blue" },
        { name: "Easy Rider", condition: "open", difficulty: "green" },
        { name: "L-Park", condition: "open", difficulty: "free-style" },
        {
          name: "Showcase Glades",
          condition: "open",
          difficulty: "double-black",
        },
        { name: "Tranquility", condition: "open", difficulty: "blue" },
        { name: "Village Way", condition: "open", difficulty: "blue" },
        { name: "Graduate", condition: "open", difficulty: "green" },
        { name: "Memory Lane", condition: "open", difficulty: "black" },
        { name: "Smart Alec", condition: "open", difficulty: "blue" },
        { name: "Undergrad", condition: "open", difficulty: "green" },
        {
          name: "Yahoo Terrain Park",
          condition: "open",
          difficulty: "free-style",
        },
        { name: "L-Hill", condition: "open", difficulty: "blue" },
        { name: "Rinus Run", condition: "open", difficulty: "black" },
        { name: "Susan's Hideaway", condition: "open", difficulty: "blue" },
        {
          name: "Village Glades",
          condition: "open",
          difficulty: "double-black",
        },
        { name: "Yahoo Trail", condition: "open", difficulty: "blue" },
        { name: "Apple Bowl", condition: "open", difficulty: "blue" },
        { name: "Due North", condition: "open", difficulty: "green" },
        { name: "Willy's", condition: "open", difficulty: "double-black" },
        { name: "Burner", condition: "open", difficulty: "black" },
        { name: "Happy Valley", condition: "open", difficulty: "green" },
        {
          name: "Calamity Lane",
          condition: "open",
          difficulty: "double-black",
        },
        { name: "Legacy", condition: "open", difficulty: "blue" },
        { name: "Dog Sled", condition: "open", difficulty: "blue" },
        {
          name: "Going South Glades",
          condition: "open",
          difficulty: "double-black",
        },
        { name: "Little Devil", condition: "open", difficulty: "double-black" },
        { name: "Senator / Larway", condition: "open", difficulty: "black" },
        { name: "Avalanche", condition: "open", difficulty: "double-black" },
        {
          name: "Elevator Shaft",
          condition: "open",
          difficulty: "double-black",
        },
        { name: "Hog's Back", condition: "open", difficulty: "black" },
        { name: "Lone Rider", condition: "open", difficulty: "double-black" },
        { name: "Rabbits Run", condition: "open", difficulty: "black" },
        { name: "Spectacular", condition: "open", difficulty: "double-black" },
        { name: "Dieppe", condition: "open", difficulty: "black" },
        { name: "Going South", condition: "open", difficulty: "blue" },
        { name: "Kandahar", condition: "open", difficulty: "black" },
        { name: "North Glades", condition: "open", difficulty: "double-black" },
        { name: "Schuss", condition: "open", difficulty: "blue" },
        {
          name: "Starting Gate",
          condition: "open",
          difficulty: "double-black",
        },
      ],
      tollFree: "1-833-583-2583",
      trailMap: blueMountainTrailMap,
      tubbingPrice: 84.84,
      website: "https://www.bluemountain.ca/",
    },
    {
      address: "5234 Kelso Rd, Milton, ON L9T 2X7",
      coordinates: { lat: 43.55418055900003, lng: -79.93414693948958 },
      dayTicketPrice: 65,
      email: "gleneden@hrca.on.ca",
      googleMapsUrl: "https://maps.app.goo.gl/B1FXSZ1VtYbVTsaXA",
      resortId: "glen-eden",
      image: glenEdenImg,
      hasAccommodations: false,
      hasCrossCountry: false,
      hasLessons: true,
      hasSnowshoeing: false,
      hasSpa: false,
      hasTubing: false,
      lessonsPrice: 125,
      name: "Glen Eden",
      phone: "(905) 878-5011",
      rating: 4.2,
      skiRentalPrice: 52,
      snowBoardRentalPrice: 52,
      runs: { black: 2, blue: 4, doubleBlack: 0, freeStyle: 17, green: 7 },
      trackConditions: [
        { name: "Escarpment Run", condition: "open", difficulty: "green" },
        { name: "Night Hawk", condition: "open", difficulty: "green" },
        { name: "Butternut", condition: "open", difficulty: "blue" },
        { name: "Falcon", condition: "open", difficulty: "blue" },
        { name: "Sidewinder", condition: "open", difficulty: "blue" },
        { name: "Twister", condition: "open", difficulty: "blue" },
        { name: "Boomerang", condition: "open", difficulty: "black" },
        { name: "Challenger", condition: "open", difficulty: "black" },
        { name: "Quarry Run", condition: "open", difficulty: "free-style" },
        { name: "Scimitar", condition: "open", difficulty: "free-style" },
        { name: "Comet", condition: "open", difficulty: "green" },
        { name: "Milky Way", condition: "open", difficulty: "green" },
        { name: "Little Dipper", condition: "open", difficulty: "free-style" },
        { name: "Shooting Star", condition: "open", difficulty: "free-style" },
        { name: "Bumble Bee", condition: "open", difficulty: "green" },
        { name: "Grasshopper", condition: "open", difficulty: "green" },
        { name: "Monarch", condition: "open", difficulty: "green" },
      ],
      trailMap: glenEdenTrailMap,
      tubbingPrice: 0,
      website: "https://gleneden.on.ca/",
    },
    {
      address: "396 Morrison Road, Kitchener, ON N2A 2Z6",
      coordinates: { lat: 43.50150295771778, lng: -80.42101373098909 },
      dayTicketPrice: 65,
      email: "guestservices@chicopee.ca",
      googleMapsUrl: "https://maps.app.goo.gl/GSNWkGQzo5aHdWmf9",
      resortId: "chicopee",
      image: chicopeeImg,
      hasAccommodations: false,
      hasCrossCountry: false,
      hasLessons: true,
      hasSnowshoeing: false,
      hasSpa: false,
      hasTubing: false,
      lessonsPrice: 350,
      name: "Chicopee",
      phone: "(519) 894-5610",
      rating: 4.2,
      skiRentalPrice: 53,
      snowBoardRentalPrice: 53,
      runs: { black: 5, blue: 5, doubleBlack: 0, freeStyle: 13, green: 3 },
      trackConditions: [
        { name: "Discover", condition: "open", difficulty: "green" },
        { name: "Adventure", condition: "open", difficulty: "green" },
        { name: "Bridge", condition: "open", difficulty: "blue" },
        { name: "Freedom", condition: "open", difficulty: "blue" },
        {
          name: "Mount St. Louis Moonstone Way",
          condition: "open",
          difficulty: "green",
        },
        { name: "Wishbone", condition: "open", difficulty: "blue" },
        { name: "Easy Rider", condition: "open", difficulty: "black" },
        { name: "North", condition: "open", difficulty: "blue" },
        { name: "Mic Mac", condition: "open", difficulty: "black" },
        { name: "Chicane", condition: "open", difficulty: "black" },
        { name: "Roughshod", condition: "open", difficulty: "black" },
        { name: "Applebowl", condition: "open", difficulty: "black" },
        { name: "Racer's Alley", condition: "open", difficulty: "blue" },
      ],
      trailMap: chicopeeTrailMap,
      tubbingPrice: 0,
      website: "http://www.discoverchicopee.com/",
    },
    {
      address: "17431 Mississauga Road, Caledon, Ontario L7K 0E9",
      coordinates: { lat: 43.856306447577786, lng: -80.00755054550318 },
      dayTicketPrice: 85,
      email: "admin@caledonskiclub.on.ca",
      googleMapsUrl: "https://maps.app.goo.gl/UqTeQ1vjSiSMV1CK7",
      resortId: "caledon-ski-club",
      image: calendonImg,
      hasAccommodations: false,
      hasCrossCountry: false,
      hasLessons: true,
      hasSnowshoeing: false,
      hasSpa: false,
      hasTubing: false,
      lessonsPrice: 0,
      name: "Caledon Ski Club",
      phone: "1-800-363-7669",
      rating: 4.6,
      skiRentalPrice: 74.99,
      snowBoardRentalPrice: 74.99,
      runs: { black: 0, blue: 0, doubleBlack: 0, freeStyle: 27, green: 27 },
      trackConditions: [
        { name: "Alley Way", condition: "open", difficulty: "green" },
        { name: "Boughner's Boogie", condition: "open", difficulty: "green" },
        { name: "Snow Park", condition: "open", difficulty: "green" },
        { name: "Dodds' Dip", condition: "open", difficulty: "green" },
        { name: "Eaton's Annex", condition: "open", difficulty: "green" },
        {
          name: "Harold's Headstander",
          condition: "open",
          difficulty: "green",
        },
        { name: "Holden's Hwy", condition: "open", difficulty: "green" },
        { name: "Kendall's Kandihar", condition: "open", difficulty: "green" },
        { name: "Kenne's Kicker", condition: "open", difficulty: "green" },
        { name: "Kids' Buel", condition: "close", difficulty: "green" },
        { name: "Knight Flight", condition: "open", difficulty: "green" },
        { name: "Larry's Line", condition: "open", difficulty: "green" },
        { name: "Lower Road", condition: "open", difficulty: "green" },
        { name: "MacKenzie Trail", condition: "open", difficulty: "green" },
        { name: "Moonbeam", condition: "open", difficulty: "green" },
        { name: "O.K. Ross Run", condition: "open", difficulty: "green" },
        { name: "Philpott's Folly", condition: "open", difficulty: "green" },
        { name: "Porter's Pipeline", condition: "open", difficulty: "green" },
        { name: "Quick Link", condition: "open", difficulty: "green" },
        { name: "Roadrunner", condition: "open", difficulty: "green" },
        { name: "Sidewinder", condition: "open", difficulty: "green" },
        { name: "Snowy's Glade", condition: "open", difficulty: "green" },
        { name: "Soules' Skyway", condition: "open", difficulty: "green" },
        {
          name: "The Yeighway Highway",
          condition: "open",
          difficulty: "green",
        },
        { name: "West Hill", condition: "open", difficulty: "green" },
        { name: "Wortley's Wiggle", condition: "open", difficulty: "green" },
        { name: "Zoe's Line", condition: "open", difficulty: "green" },
      ],
      trailMap: calendonTrailMap,
      tubbingPrice: 0,
      website: "http://caledonskiclub.com/",
    },
  ];
}
