import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/header";
import ConvexClientProvider from "./ConvexClientProvider";
import { FiltersProvider } from "@/src/features/common/context/filtersContext";
import { LanguageProvider } from "@/src/i18n";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <ConvexClientProvider>
            <LanguageProvider>
              <FiltersProvider>
                <div className="min-h-screen bg-background">
                  <Header />
                  {children}
                </div>
              </FiltersProvider>
            </LanguageProvider>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
