import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/header";
import ConvexClientProvider from "./ConvexClientProvider";
import { FiltersProvider } from "@/src/features/common/context/filtersContext";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConvexClientProvider>
          <FiltersProvider>
            <div className="min-h-screen bg-background">
              <Header />
              {children}
            </div>
          </FiltersProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
